services:
  postgres:
    image: postgres
    container_name: t3-sample-postgres-for-front-docker
    environment:
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  myapp-frontend:
    image: myapp-frontend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:your_password@postgres:5432/t3-sample
