# Build stage
FROM --platform=linux/amd64 node:20-alpine AS build
WORKDIR /app

# Install yarn
RUN corepack enable
RUN corepack prepare yarn@4.3.1 --activate

# Copy package.json and yarn.lock
COPY . .

# Install dependencies
RUN yarn install --immutable

# Copy the rest of the application code
COPY . .

# Build the application
RUN yarn build

# Production stage
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
EXPOSE 80
